item {
    name: "door",
    id: 1,
    display_name: "door"
}
item {
    name: "person",
    id: 2,
    display_name: "person"
}
item {
    name: "pig",
    id: 3,
    display_name: "pig"
}
item {
    name: "white",
    id: 4,
    display_name: "white"
}
